# Generated by Django 4.1.3 on 2022-12-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='count',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
